### ISSUE TITLE
[BUG] Pirates is missing

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-runner#71]
throw err;
    ^

Error: Cannot find module 'pirates'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pfeldman/code/playwright-cli/node_modules/@playwright/test-runner/out/transform.js:42:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by pavelfeldman** [comment]
@babel/core - same

**Comment by mxschmitt** [comment]
Good catch, I updated #70 should be fixed then.
